name: Prettier Formatting

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check formatting using prettier
        uses: actionsx/prettier@v3
        with:
          args: --check .
